import { Standing } from './models/standings';

export const standingsConstArray: Standing[] = [
    {
        rank: 1,
        team: {
            id: 50,
            name: 'Manchester City',
            logo: 'https://media-4.api-sports.io/football/teams/50.png',
        },
        points: 18,
        goalsDiff: 13,
        group: 'Premier League',
        form: 'WWWWW',
        status: 'same',
        description: 'Promotion - Champions League (Group Stage: )',
        all: {
            played: 6,
            win: 6,
            draw: 0,
            lose: 0,
            goals: {
                for: 16,
                against: 3,
            },
        },
        home: {
            played: 3,
            win: 3,
            draw: 0,
            lose: 0,
            goals: {
                for: 8,
                against: 1,
            },
        },
        away: {
            played: 3,
            win: 3,
            draw: 0,
            lose: 0,
            goals: {
                for: 8,
                against: 2,
            },
        },
        update: new Date('2023-09-24T00:00:00+00:00'),
    },
    {
        rank: 2,
        team: {
            id: 40,
            name: 'Liverpool',
            logo: 'https://media-4.api-sports.io/football/teams/40.png',
        },
        points: 16,
        goalsDiff: 10,
        group: 'Premier League',
        form: 'WWWWW',
        status: 'same',
        description: 'Promotion - Champions League (Group Stage: )',
        all: {
            played: 6,
            win: 5,
            draw: 1,
            lose: 0,
            goals: {
                for: 15,
                against: 5,
            },
        },
        home: {
            played: 3,
            win: 3,
            draw: 0,
            lose: 0,
            goals: {
                for: 9,
                against: 2,
            },
        },
        away: {
            played: 3,
            win: 2,
            draw: 1,
            lose: 0,
            goals: {
                for: 6,
                against: 3,
            },
        },
        update: new Date('2023-09-24T00:00:00+00:00'),
    },
    {
        rank: 3,
        team: {
            id: 51,
            name: 'Brighton',
            logo: 'https://media-4.api-sports.io/football/teams/51.png',
        },
        points: 15,
        goalsDiff: 10,
        group: 'Premier League',
        form: 'WWWLW',
        status: 'same',
        description: 'Promotion - Champions League (Group Stage: )',
        all: {
            played: 6,
            win: 5,
            draw: 0,
            lose: 1,
            goals: {
                for: 18,
                against: 8,
            },
        },
        home: {
            played: 4,
            win: 3,
            draw: 0,
            lose: 1,
            goals: {
                for: 11,
                against: 6,
            },
        },
        away: {
            played: 2,
            win: 2,
            draw: 0,
            lose: 0,
            goals: {
                for: 7,
                against: 2,
            },
        },
        update: new Date('2023-09-24T00:00:00+00:00'),
    },
    {
        rank: 1,
        team: {
            id: 50,
            name: 'Manchester City',
            logo: 'https://media-4.api-sports.io/football/teams/50.png',
        },
        points: 18,
        goalsDiff: 13,
        group: 'Premier League',
        form: 'WWWWW',
        status: 'same',
        description: 'Promotion - Champions League (Group Stage: )',
        all: {
            played: 6,
            win: 6,
            draw: 0,
            lose: 0,
            goals: {
                for: 16,
                against: 3,
            },
        },
        home: {
            played: 3,
            win: 3,
            draw: 0,
            lose: 0,
            goals: {
                for: 8,
                against: 1,
            },
        },
        away: {
            played: 3,
            win: 3,
            draw: 0,
            lose: 0,
            goals: {
                for: 8,
                against: 2,
            },
        },
        update: new Date('2023-09-24T00:00:00+00:00'),
    },
    {
        rank: 2,
        team: {
            id: 40,
            name: 'Liverpool',
            logo: 'https://media-4.api-sports.io/football/teams/40.png',
        },
        points: 16,
        goalsDiff: 10,
        group: 'Premier League',
        form: 'WWWWW',
        status: 'same',
        description: 'Promotion - Champions League (Group Stage: )',
        all: {
            played: 6,
            win: 5,
            draw: 1,
            lose: 0,
            goals: {
                for: 15,
                against: 5,
            },
        },
        home: {
            played: 3,
            win: 3,
            draw: 0,
            lose: 0,
            goals: {
                for: 9,
                against: 2,
            },
        },
        away: {
            played: 3,
            win: 2,
            draw: 1,
            lose: 0,
            goals: {
                for: 6,
                against: 3,
            },
        },
        update: new Date('2023-09-24T00:00:00+00:00'),
    },
    {
        rank: 3,
        team: {
            id: 51,
            name: 'Brighton',
            logo: 'https://media-4.api-sports.io/football/teams/51.png',
        },
        points: 15,
        goalsDiff: 10,
        group: 'Premier League',
        form: 'WWWLW',
        status: 'same',
        description: 'Promotion - Champions League (Group Stage: )',
        all: {
            played: 6,
            win: 5,
            draw: 0,
            lose: 1,
            goals: {
                for: 18,
                against: 8,
            },
        },
        home: {
            played: 4,
            win: 3,
            draw: 0,
            lose: 1,
            goals: {
                for: 11,
                against: 6,
            },
        },
        away: {
            played: 2,
            win: 2,
            draw: 0,
            lose: 0,
            goals: {
                for: 7,
                against: 2,
            },
        },
        update: new Date('2023-09-24T00:00:00+00:00'),
    },
    {
        rank: 1,
        team: {
            id: 50,
            name: 'Manchester City',
            logo: 'https://media-4.api-sports.io/football/teams/50.png',
        },
        points: 18,
        goalsDiff: 13,
        group: 'Premier League',
        form: 'WWWWW',
        status: 'same',
        description: 'Promotion - Champions League (Group Stage: )',
        all: {
            played: 6,
            win: 6,
            draw: 0,
            lose: 0,
            goals: {
                for: 16,
                against: 3,
            },
        },
        home: {
            played: 3,
            win: 3,
            draw: 0,
            lose: 0,
            goals: {
                for: 8,
                against: 1,
            },
        },
        away: {
            played: 3,
            win: 3,
            draw: 0,
            lose: 0,
            goals: {
                for: 8,
                against: 2,
            },
        },
        update: new Date('2023-09-24T00:00:00+00:00'),
    },
    {
        rank: 2,
        team: {
            id: 40,
            name: 'Liverpool',
            logo: 'https://media-4.api-sports.io/football/teams/40.png',
        },
        points: 16,
        goalsDiff: 10,
        group: 'Premier League',
        form: 'WWWWW',
        status: 'same',
        description: 'Promotion - Champions League (Group Stage: )',
        all: {
            played: 6,
            win: 5,
            draw: 1,
            lose: 0,
            goals: {
                for: 15,
                against: 5,
            },
        },
        home: {
            played: 3,
            win: 3,
            draw: 0,
            lose: 0,
            goals: {
                for: 9,
                against: 2,
            },
        },
        away: {
            played: 3,
            win: 2,
            draw: 1,
            lose: 0,
            goals: {
                for: 6,
                against: 3,
            },
        },
        update: new Date('2023-09-24T00:00:00+00:00'),
    },
    {
        rank: 3,
        team: {
            id: 51,
            name: 'Brighton',
            logo: 'https://media-4.api-sports.io/football/teams/51.png',
        },
        points: 15,
        goalsDiff: 10,
        group: 'Premier League',
        form: 'WWWLW',
        status: 'same',
        description: 'Promotion - Champions League (Group Stage: )',
        all: {
            played: 6,
            win: 5,
            draw: 0,
            lose: 1,
            goals: {
                for: 18,
                against: 8,
            },
        },
        home: {
            played: 4,
            win: 3,
            draw: 0,
            lose: 1,
            goals: {
                for: 11,
                against: 6,
            },
        },
        away: {
            played: 2,
            win: 2,
            draw: 0,
            lose: 0,
            goals: {
                for: 7,
                against: 2,
            },
        },
        update: new Date('2023-09-24T00:00:00+00:00'),
    },
    {
        rank: 1,
        team: {
            id: 50,
            name: 'Manchester City',
            logo: 'https://media-4.api-sports.io/football/teams/50.png',
        },
        points: 18,
        goalsDiff: 13,
        group: 'Premier League',
        form: 'WWWWW',
        status: 'same',
        description: 'Promotion - Champions League (Group Stage: )',
        all: {
            played: 6,
            win: 6,
            draw: 0,
            lose: 0,
            goals: {
                for: 16,
                against: 3,
            },
        },
        home: {
            played: 3,
            win: 3,
            draw: 0,
            lose: 0,
            goals: {
                for: 8,
                against: 1,
            },
        },
        away: {
            played: 3,
            win: 3,
            draw: 0,
            lose: 0,
            goals: {
                for: 8,
                against: 2,
            },
        },
        update: new Date('2023-09-24T00:00:00+00:00'),
    },
    {
        rank: 2,
        team: {
            id: 40,
            name: 'Liverpool',
            logo: 'https://media-4.api-sports.io/football/teams/40.png',
        },
        points: 16,
        goalsDiff: 10,
        group: 'Premier League',
        form: 'WWWWW',
        status: 'same',
        description: 'Promotion - Champions League (Group Stage: )',
        all: {
            played: 6,
            win: 5,
            draw: 1,
            lose: 0,
            goals: {
                for: 15,
                against: 5,
            },
        },
        home: {
            played: 3,
            win: 3,
            draw: 0,
            lose: 0,
            goals: {
                for: 9,
                against: 2,
            },
        },
        away: {
            played: 3,
            win: 2,
            draw: 1,
            lose: 0,
            goals: {
                for: 6,
                against: 3,
            },
        },
        update: new Date('2023-09-24T00:00:00+00:00'),
    },
    {
        rank: 3,
        team: {
            id: 51,
            name: 'Brighton',
            logo: 'https://media-4.api-sports.io/football/teams/51.png',
        },
        points: 15,
        goalsDiff: 10,
        group: 'Premier League',
        form: 'WWWLW',
        status: 'same',
        description: 'Promotion - Champions League (Group Stage: )',
        all: {
            played: 6,
            win: 5,
            draw: 0,
            lose: 1,
            goals: {
                for: 18,
                against: 8,
            },
        },
        home: {
            played: 4,
            win: 3,
            draw: 0,
            lose: 1,
            goals: {
                for: 11,
                against: 6,
            },
        },
        away: {
            played: 2,
            win: 2,
            draw: 0,
            lose: 0,
            goals: {
                for: 7,
                against: 2,
            },
        },
        update: new Date('2023-09-24T00:00:00+00:00'),
    },
    {
        rank: 1,
        team: {
            id: 50,
            name: 'Manchester City',
            logo: 'https://media-4.api-sports.io/football/teams/50.png',
        },
        points: 18,
        goalsDiff: 13,
        group: 'Premier League',
        form: 'WWWWW',
        status: 'same',
        description: 'Promotion - Champions League (Group Stage: )',
        all: {
            played: 6,
            win: 6,
            draw: 0,
            lose: 0,
            goals: {
                for: 16,
                against: 3,
            },
        },
        home: {
            played: 3,
            win: 3,
            draw: 0,
            lose: 0,
            goals: {
                for: 8,
                against: 1,
            },
        },
        away: {
            played: 3,
            win: 3,
            draw: 0,
            lose: 0,
            goals: {
                for: 8,
                against: 2,
            },
        },
        update: new Date('2023-09-24T00:00:00+00:00'),
    },
    {
        rank: 2,
        team: {
            id: 40,
            name: 'Liverpool',
            logo: 'https://media-4.api-sports.io/football/teams/40.png',
        },
        points: 16,
        goalsDiff: 10,
        group: 'Premier League',
        form: 'WWWWW',
        status: 'same',
        description: 'Promotion - Champions League (Group Stage: )',
        all: {
            played: 6,
            win: 5,
            draw: 1,
            lose: 0,
            goals: {
                for: 15,
                against: 5,
            },
        },
        home: {
            played: 3,
            win: 3,
            draw: 0,
            lose: 0,
            goals: {
                for: 9,
                against: 2,
            },
        },
        away: {
            played: 3,
            win: 2,
            draw: 1,
            lose: 0,
            goals: {
                for: 6,
                against: 3,
            },
        },
        update: new Date('2023-09-24T00:00:00+00:00'),
    },
    {
        rank: 3,
        team: {
            id: 51,
            name: 'Brighton',
            logo: 'https://media-4.api-sports.io/football/teams/51.png',
        },
        points: 15,
        goalsDiff: 10,
        group: 'Premier League',
        form: 'WWWLW',
        status: 'same',
        description: 'Promotion - Champions League (Group Stage: )',
        all: {
            played: 6,
            win: 5,
            draw: 0,
            lose: 1,
            goals: {
                for: 18,
                against: 8,
            },
        },
        home: {
            played: 4,
            win: 3,
            draw: 0,
            lose: 1,
            goals: {
                for: 11,
                against: 6,
            },
        },
        away: {
            played: 2,
            win: 2,
            draw: 0,
            lose: 0,
            goals: {
                for: 7,
                against: 2,
            },
        },
        update: new Date('2023-09-24T00:00:00+00:00'),
    },
    {
        rank: 1,
        team: {
            id: 50,
            name: 'Manchester City',
            logo: 'https://media-4.api-sports.io/football/teams/50.png',
        },
        points: 18,
        goalsDiff: 13,
        group: 'Premier League',
        form: 'WWWWW',
        status: 'same',
        description: 'Promotion - Champions League (Group Stage: )',
        all: {
            played: 6,
            win: 6,
            draw: 0,
            lose: 0,
            goals: {
                for: 16,
                against: 3,
            },
        },
        home: {
            played: 3,
            win: 3,
            draw: 0,
            lose: 0,
            goals: {
                for: 8,
                against: 1,
            },
        },
        away: {
            played: 3,
            win: 3,
            draw: 0,
            lose: 0,
            goals: {
                for: 8,
                against: 2,
            },
        },
        update: new Date('2023-09-24T00:00:00+00:00'),
    },
    {
        rank: 2,
        team: {
            id: 40,
            name: 'Liverpool',
            logo: 'https://media-4.api-sports.io/football/teams/40.png',
        },
        points: 16,
        goalsDiff: 10,
        group: 'Premier League',
        form: 'WWWWW',
        status: 'same',
        description: 'Promotion - Champions League (Group Stage: )',
        all: {
            played: 6,
            win: 5,
            draw: 1,
            lose: 0,
            goals: {
                for: 15,
                against: 5,
            },
        },
        home: {
            played: 3,
            win: 3,
            draw: 0,
            lose: 0,
            goals: {
                for: 9,
                against: 2,
            },
        },
        away: {
            played: 3,
            win: 2,
            draw: 1,
            lose: 0,
            goals: {
                for: 6,
                against: 3,
            },
        },
        update: new Date('2023-09-24T00:00:00+00:00'),
    },
    {
        rank: 3,
        team: {
            id: 51,
            name: 'Brighton',
            logo: 'https://media-4.api-sports.io/football/teams/51.png',
        },
        points: 15,
        goalsDiff: 10,
        group: 'Premier League',
        form: 'WWWLW',
        status: 'same',
        description: 'Promotion - Champions League (Group Stage: )',
        all: {
            played: 6,
            win: 5,
            draw: 0,
            lose: 1,
            goals: {
                for: 18,
                against: 8,
            },
        },
        home: {
            played: 4,
            win: 3,
            draw: 0,
            lose: 1,
            goals: {
                for: 11,
                against: 6,
            },
        },
        away: {
            played: 2,
            win: 2,
            draw: 0,
            lose: 0,
            goals: {
                for: 7,
                against: 2,
            },
        },
        update: new Date('2023-09-24T00:00:00+00:00'),
    },
    {
        rank: 1,
        team: {
            id: 50,
            name: 'Manchester City',
            logo: 'https://media-4.api-sports.io/football/teams/50.png',
        },
        points: 18,
        goalsDiff: 13,
        group: 'Premier League',
        form: 'WWWWW',
        status: 'same',
        description: 'Promotion - Champions League (Group Stage: )',
        all: {
            played: 6,
            win: 6,
            draw: 0,
            lose: 0,
            goals: {
                for: 16,
                against: 3,
            },
        },
        home: {
            played: 3,
            win: 3,
            draw: 0,
            lose: 0,
            goals: {
                for: 8,
                against: 1,
            },
        },
        away: {
            played: 3,
            win: 3,
            draw: 0,
            lose: 0,
            goals: {
                for: 8,
                against: 2,
            },
        },
        update: new Date('2023-09-24T00:00:00+00:00'),
    },
    {
        rank: 2,
        team: {
            id: 40,
            name: 'Liverpool',
            logo: 'https://media-4.api-sports.io/football/teams/40.png',
        },
        points: 16,
        goalsDiff: 10,
        group: 'Premier League',
        form: 'WWWWW',
        status: 'same',
        description: 'Promotion - Champions League (Group Stage: )',
        all: {
            played: 6,
            win: 5,
            draw: 1,
            lose: 0,
            goals: {
                for: 15,
                against: 5,
            },
        },
        home: {
            played: 3,
            win: 3,
            draw: 0,
            lose: 0,
            goals: {
                for: 9,
                against: 2,
            },
        },
        away: {
            played: 3,
            win: 2,
            draw: 1,
            lose: 0,
            goals: {
                for: 6,
                against: 3,
            },
        },
        update: new Date('2023-09-24T00:00:00+00:00'),
    },
    {
        rank: 3,
        team: {
            id: 51,
            name: 'Brighton',
            logo: 'https://media-4.api-sports.io/football/teams/51.png',
        },
        points: 15,
        goalsDiff: 10,
        group: 'Premier League',
        form: 'WWWLW',
        status: 'same',
        description: 'Promotion - Champions League (Group Stage: )',
        all: {
            played: 6,
            win: 5,
            draw: 0,
            lose: 1,
            goals: {
                for: 18,
                against: 8,
            },
        },
        home: {
            played: 4,
            win: 3,
            draw: 0,
            lose: 1,
            goals: {
                for: 11,
                against: 6,
            },
        },
        away: {
            played: 2,
            win: 2,
            draw: 0,
            lose: 0,
            goals: {
                for: 7,
                against: 2,
            },
        },
        update: new Date('2023-09-24T00:00:00+00:00'),
    },
];
